### ISSUE TITLE
edit-indirect-region, how to force it to open in other-window

### ISSUE THREAD

**Issue by agzam** [Fanael/edit-indirect#12]
edit-indirect-region replaces current window on my machine, how do I force it to open in other-window instead?

**Comment by Fanael** [comment]
`edit-indirect` uses [`display-buffer`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Choosing-Window.html), so the usual customization options of `display-buffer` apply, like `display-buffer-alist`.
