### ISSUE TITLE
quit-window called even if no window was created

### ISSUE THREAD

**Issue by gvol** [Fanael/edit-indirect#2]
I have the following minimal example of something that I want to do.  The intention is to indent (a portion of) the buffer with another major-mode.  But `edit-indirect-commit` calls quit-window which buries the buffer I'm working in.

    (with-current-buffer
        (edit-indirect-region (point-min) (point-max) nil)
      (indent-region (point-min) (point-max))
      (edit-indirect-commit))

**Comment by Fanael** [comment]
Good catch.

**Comment by gvol** [comment]
Sweet, thanks!
