### ISSUE TITLE
Make it easy to switch to an existing indirect edit buffer

### ISSUE THREAD

**Issue by mathrick** [Fanael/edit-indirect#22]
Currently, when an indirect edit buffer exists for a region, an overlay is created, but it doesn't provide any way to switch to the corresponding buffer. This means that any keypress will simply result in the error message that the area is read-only, and it's on me to find the corresponding buffer. This can be surprisingly hard when I have long-lived indirect edit buffer (I happen to be writing python code packaged in a YAML container, so my edits are pretty lengthy and can stretch until the next day before I commit).

It would be very handy if there was a function to switch to the overlay's edit buffer, ideally bound to something obvious like <kbd>RET</kbd> inside the overlay.

**Comment by Fanael** [comment]
If you call `edit-indirect-region` with a region having an edit-indirect buffer being the active region, it will switch to the existing buffer.
