### ISSUE TITLE
Enhance "save-buffer" behavior

### ISSUE THREAD

**Issue by ryanprior** [Fanael/edit-indirect#8]
When I edit in an indirect buffer and try to `save-buffer` I get prompted for a file name to save to, which reminds me that what I really wanted to do is to <kbd>C-c</kbd> <kbd>'</kbd>.

However, is anybody really saving their indirect buffers to disk? It seems to me like the more expected and useful behavior would be to replace the code block we're indirect-editing and mark the indirect buffer as saved, but not close it.

If what you really want is to write to disk, you should `write-file` instead of `save-buffer`. Does that make sense?

**Comment by Flupp** [comment]
Isn’t this fixed by de645d8144e8a08f039a9c88185121ec81d957ef?

**Comment by wbolster** [comment]
seems so indeed, but ideally it should be using a [remap] binding instead.

**Comment by Fanael** [comment]
@wbolster That's a good point, I simply forgot remap bindings existed. Should be fixed now.

**Comment by ryanprior** [comment]
Just tried this the other day, works great! Thank you @dakra & @Fanael this package is a long time favorite!
